### ISSUE TITLE
Bulk generating?

### ISSUE THREAD

**Issue by ghost** [Dendroidal/Jap-jap-definition-scraper-from-weblio--Anki-add-on-#1]
Is there any way to do a bulk fetch?
I have over 20.000 cards and doing this manually would be very tiresome.
Thanks!

**Comment by Dendroidal** [comment]
Hi yaoberh,

I didn't implement bulk fetch since I don't use it (I also have around 20.000 cards, but I usually edit cards only when I spot issues), though it shouldn't be too hard to add it to the add-on.

However, my use scenario is that I make cards with full sentences and then select the few words whose definitions I want to fetch.

What is your use case for bulk fetch? Would your cards include full sentences or only a few words? Because in the former case I'm not sure how bulk fetch would work.

**Comment by ghost** [comment]
I have an Expression field which contains a single word or vocab word only. No sentences in any of them, those are in a different field and created by Bulk Generate Japanese Examples addon.
So basically it would just be that the Words field is actually my Expression field in all cases. I don't have 2 different fields for those.
Basically what I would like is having the definition of the vocabulary expression or kanji put into another field automatically.

**Comment by Dendroidal** [comment]
Ok, got it. In that case that definitely sounds like something I should be able to set up.

It will take me a little time to learn the proper way of implementing that in Anki, but I'll put it on my "to do" list.

**Comment by ghost** [comment]
Thank you so much! So I'll get an update notification in anki right?
Thanks again!

**Comment by ghost** [comment]
There's another addon which does the same as yours but it's not working anymore:
https://ankiweb.net/shared/info/2055037404
Maybe this helps you.

**Comment by Dendroidal** [comment]
I'm aware of that add-on, yes. 
It actually helped me in writing my add-on, though most of my work was in getting the formatting to work, which that add-on doesn't do, and which took me considerable effort.

Either way, I'll be looking into how that add-on implements bulk readings to see how to implement that feature.

**Comment by Dendroidal** [comment]
Hi yaoberh,

Not sure if Anki gave you a notice or not, but I've now updated the add-on to include bulk fetch functionality. I'll update the ankiweb post explaining it better latter (and clean a few other things), but you should now be able to use the bulk fetch: when browsing the cards just select the notes in question and right click and you should see the option to "Regenerate definitions" (alternatively, you can find that option in the Edit menu). As in the ankiweb post, the add-on will fetch the words in the Words field (which can be multiple, separated by 、) and return the formatted definitions in the "Meaning" field.

Let me know if you have any other questions, or run into issues.
